version: "2"
services:
    tomcat:
        image: "jamj2000/tomcat:fpbasics"
        ports:
            - "8080:8080"
        depends_on:
            - sqlserver
    sqlserver:
        image: "jamj2000/sqlserver:fpbasics"
        environment:
            SA_PASSWORD: "Temporal22"
            ACCEPT_EULA: "Y"
