version: "2"
services:
    tomcat:
        image: "tomcat:8.0-jre8"
#        image: "tomcat:fpbasics"
        ports:
            - "8080:8080"
        depends_on:
            - sqlserver
    sqlserver:
        image: "microsoft/mssql-server-linux:2017-latest"
#        image: "sqlserver:fpbasics"
        environment:
            SA_PASSWORD: "Temporal22"
            ACCEPT_EULA: "Y"
