CREATE TABLE FORMADORES
(
    ID_FORMADOR   NUMBER(3),
    NOMBRE   VARCHAR(30),
    APELLIDOS   VARCHAR(30),
    TELEFONO   NUMBER(9),
    EMAIL   VARCHAR(30),
    CONSTRAINT pk_formador PRIMARY KEY(ID_FORMADOR)
);

CREATE TABLE MODULOS
(
    ID_MODULO   NUMBER(3),
    NOMBRE   VARCHAR(30),
    DURACION   NUMBER(3,1),
    CURSO   VARCHAR(2),
    CONSTRAINT pk_modulo PRIMARY KEY(ID_MODULO)
);

CREATE TABLE BLOQUES
(
    EMPRESA                 VARCHAR(20),
    ID_BLOQUE               NUMBER(3),
    ID_MODULO               NUMBER(3),
    DESCRIPCION             VARCHAR(100),
	ORDEN                   VARCHAR(3),
    ID_FORMADOR_RESPONSABLE NUMBER(3),
    CONSTRAINT pk_bloques PRIMARY KEY(EMPRESA, ID_BLOQUE),
    CONSTRAINT fk1_bloques FOREIGN KEY(ID_MODULO) REFERENCES MODULOS(ID_MODULO),
    CONSTRAINT fk2_formadores FOREIGN KEY(ID_FORMADOR_RESPONSABLE) REFERENCES FORMADORES(ID_FORMADOR),
    CONSTRAINT uq_bloques UNIQUE (ORDEN)
);

CREATE TABLE RESULTADOS_APRENDIZAJE
(
    ID_RESULTADOS  NUMBER(3),
    ID_MODULO      NUMBER(3),
    DESCRIPCION    VARCHAR(100),
    CONSTRAINT pk_resultados PRIMARY KEY(ID_RESULTADOS,ID_MODULO),
    CONSTRAINT fk_modulo FOREIGN KEY(ID_MODULO) REFERENCES MODULOS(ID_MODULO) ON DELETE CASCADE
);

CREATE TABLE ACTIVIDADES_FORMATIVAS
(
    ID_ACTIVIDAD            NUMBER(3),
    EMPRESA                 VARCHAR(20),
    ID_BLOQUE               NUMBER(3),
    DESCRIPCION_ACTIVIDAD   VARCHAR(100),
    HORAS_DEDICADAS         NUMBER(3,1),
    CONSTRAINT pk_actividades PRIMARY KEY(ID_ACTIVIDAD, EMPRESA, ID_BLOQUE),
    CONSTRAINT fk_actividades FOREIGN KEY(EMPRESA, ID_BLOQUE) REFERENCES BLOQUES(EMPRESA, ID_BLOQUE) ON DELETE CASCADE
);

CREATE TABLE ACTIVIDADES_FORMADORES
(
    ID_FORMADOR   NUMBER(3),
    ID_ACTIVIDAD  NUMBER(3),
    EMPRESA       VARCHAR(20),
    ID_BLOQUE     NUMBER(3),
    CONSTRAINT pk_actividades_formadores PRIMARY KEY(ID_FORMADOR, ID_ACTIVIDAD),
    CONSTRAINT fk1_actividades_formadores FOREIGN KEY(ID_FORMADOR) REFERENCES FORMADORES(ID_FORMADOR) ON DELETE CASCADE,
    CONSTRAINT fk2_actividades_formadores FOREIGN KEY(ID_ACTIVIDAD, EMPRESA, ID_BLOQUE) REFERENCES ACTIVIDADES_FORMATIVAS(ID_ACTIVIDAD,EMPRESA, ID_BLOQUE) ON DELETE CASCADE
);
